apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deploy
  labels:
    app: app-cdps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-cdps
  template:
    metadata:
      labels:
        app: app-cdps
    spec:
    # Especificaciones de los contenedores del pod
      containers:
      - name: productpage
      # Imagen del contenedor
        image: 17/productpage
      # Para coger la imagen desde entorno minikube local
        imagePullPolicy: Never

        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: svcnodeport
spec:
  type: NodePort
  selector:
    app: app-cdps
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9080
