apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
  labels:
    app: details
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
  template:
    metadata:
      labels:
        app: details
    spec:
      containers:
      - name: 17-details
        image: 17/details
        env:
          - name: SERVICE_VERSION
            value: "v2"
          - name: ENABLE_EXTERNAL_BOOK_SERVICE
            value: "true"
        imagePullPolicy: Never
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    app: details
    service: details
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: details