apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deploy
  labels:
    app: app-cdps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-cdps
  template:
    metadata:
      labels:
        app: app-cdps
    spec:
      containers:
      - name: productpage
        image: 17/product
        imagePullPolicy: Never
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: svcnodeport
spec:
  type: NodePort
  selector:
    app: app-cdps
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9080
